name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build
      run: |
        make
        tar czf histree-core.tar.gz bin/histree-core README.md LICENSE

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        files: |
          histree-core.tar.gz
        draft: false
        prerelease: false
        body: |
          ## Changes in ${{ steps.get_version.outputs.VERSION }}

          For a detailed list of changes, please see [CHANGELOG.md](CHANGELOG.md)
